/* Visit-only demo decisions and deterministic discovery; no placement or service writes. */
(function(){'use strict';
const F=window.EdgeFinderFixtures,S=window.EdgeFinderStrings,R=F.rules;
let host=null,observer=null,sheetLock=null;
const state={filter:'all',query:'',limit:R.batch,open:null,drafts:{},decisions:[],keys:{},reasonDrafts:{},askWhy:true,selected:null,detailLadders:{},detailScroll:{},historyMode:{},historyViews:{},offerSheet:null,offerTakes:{},ownedExpanded:false,pulse:true};
const copy=x=>JSON.parse(JSON.stringify(x)),esc=x=>host.esc(x==null?'':x),pct=x=>Number.isFinite(x)?(x*100).toFixed(1)+'%':'—',signed=x=>x>0?'+'+x:String(x);
const byId=id=>F.cards.find(c=>c.id===id),decision=id=>state.decisions.find(d=>d.id===id);
function button(act,label,value,extra){return '<button data-act="ef-'+act+'"'+(value==null?'':' data-value="'+esc(value)+'"')+(extra||'')+'>'+label+'</button>';}
function reminder(){return '<span class="stake-reminder">Real bets placed elsewhere</span>';}
function number(x){if(x===null||x===undefined||String(x).trim()==='')return null;const n=Number(x);return Number.isFinite(n)?n:null;}
function breakEven(odds){const n=number(odds);if(n===null||Math.abs(n)<100)return null;const p=n>0?100/(n+100):1/(1+100/Math.abs(n));return Number.isFinite(p)&&p>0?p:null;}
function payout(legs,stake){let total=stake;for(const l of legs){if(breakEven(l.odds)===null)return null;total*=l.odds>0?1+l.odds/100:1+100/Math.abs(l.odds);}return Number.isFinite(total)?total:null;}
function exactPrice(legs){
 const pricing=window.EdgeFinderPricing;if(!pricing)return null;
 const probabilities=legs.map(l=>l.p_at_line).sort((a,b)=>a-b);
 if(probabilities.some(p=>!Number.isFinite(p)||p<0||p>1))return null;
 const key=probabilities.map(p=>p.toFixed(3)).join('|'),row=pricing.bank[key];
 if(!row||row[0].length!==probabilities.length||row[0].some((p,i)=>p!==probabilities[i]))return null;
 return {probabilities:row[0].slice(),p_joint:row[1],p_product:row[2],buckets:row[3].slice(),trace:pricing.samples.map((n,i)=>[n,row[4][i]]),method:pricing.method,disclosure:pricing.disclosure,illustrative_reveal:true};
}
function historyKey(leg){return encodeURIComponent(leg.player)+'~'+encodeURIComponent(leg.market);}
function historyChart(leg,key){key=historyKey(leg);const view=state.historyViews[key]||(state.historyViews[key]={level:'recent',season:2025}),past=state.historyMode[key]==='past',h=window.OutlookHistory;
const control=(label,level)=>button('history-level',label,key+'|'+level,' aria-pressed="'+(view.level===level)+'"');
let body=view.level==='annual'?'<div class="ef-season-list">'+[2023,2024,2025].map(year=>{const r=h.seasonSummary(leg,past,year);return button('history-season','<strong>'+year+'</strong><span><b>'+(r.percent===null?'—':r.percent.toFixed(1)+'%')+'</b><small>'+r.hits+' of '+r.available+' hit</small><i style="--history-hit:'+(r.percent||0)+'%"></i></span>',key+'|'+year);}).join('')+'</div>':view.level==='season'?h.seasonGames(leg,past,view.season):h.plot(leg,past,2025);
return '<section class="ef-history"><div class="ef-inline-actions">'+button('history-mode','Against your line',key+'|current',' aria-pressed="'+!past+'"')+button('history-mode','Past lines',key+'|past',' aria-pressed="'+past+'"')+'</div><nav class="ef-history-navigation">'+control(view.level==='season'?'All seasons':'By season','annual')+control('Recent games','recent')+'</nav><p class="ef-caption">Fictional sample history · 2023–2025 · '+esc(leg.side+' '+leg.market)+'</p>'+body+'<div class="ef-price-readout"><div><span>Model chance</span><strong>'+pct(leg.p_at_line)+'</strong></div><div><span>Chance your price needs</span><strong>'+pct(breakEven(leg.odds))+'</strong></div></div></section>';}
function gap(c){return Number.isFinite(c.p_at_line)&&Number.isFinite(c.p_fair)?Math.round((c.p_at_line-c.p_fair)*1000000)/10000:0;}
function blind(c){return !!c.blind_spot||gap(c)>=R.blind_gap;}
function bolts(c){const g=gap(c);let n=g<=0?0:1;R.bolt_thresholds.slice(1).forEach((t,i)=>{if(g>=t)n=i+2;});if(c.calibration_status!=='sample-checked')n=Math.min(n,R.unverified_cap);return blind(c)?Math.min(n,R.blind_cap):n;}
function draft(c){return state.drafts[c.id]||(state.drafts[c.id]={line:c.line,odds:String(c.odds),touched:false,take:null,riders:false});}
function filtered(){const q=state.query.trim().toLowerCase();return F.cards.filter(c=>!(draft(c).take&&decision(draft(c).take).done)&&(!q||[c.name,c.team,c.opponent].join(' ').toLowerCase().includes(q))&&(state.filter==='all'||state.filter==='tonight'&&c.tonight||state.filter==='safe'&&c.p_at_line>=R.safe||state.filter==='long'&&c.p_at_line<R.long_shot)).sort((a,b)=>Number(blind(a))-Number(blind(b))||bolts(b)-bolts(a)||gap(b)-gap(a)||F.cards.indexOf(a)-F.cards.indexOf(b));}
function hero(){return filtered().find(c=>c.tonight&&!blind(c)&&Number.isFinite(c.p_at_line)&&gap(c)>0)||null;}
function visible(){const all=filtered(),best=hero();return (best?[best].concat(all.filter(c=>c.id!==best.id)):all).slice(0,state.limit);}
function eligible(f){const historical=f.historical||f.class_id==='share-level';return !!S.templates[f.template_id]&&Object.keys(S.templates).includes(f.class_id)&&f.class_id===f.template_id&&f.season!==2025&&!/pff|home.away/i.test(f.source||'')&&(!historical||(Number.isFinite(f.n)&&f.n>=R.n_floor&&[2023,2024].includes(f.season)))&&Number.isFinite(f.surprise)&&f.measure_id;}
function angles(c){if(gap(c)<=0)return [];const facts=(c.facts||[]).filter(f=>eligible(f)&&(!f.line_sensitive||f.line===draft(c).line)).sort((a,b)=>b.surprise-a.surprise);const selected=(c.selected_angle_ids||[]).map(id=>facts.find(f=>f.id===id));if(selected.length!==2||selected.some(f=>!f)||selected[0].class_id===selected[1].class_id||selected[0].measure_id===selected[1].measure_id)return [];const top=facts[0],next=facts.find(f=>f.class_id!==top.class_id&&f.measure_id!==top.measure_id);if(!next||selected[0].id!==top.id||selected[1].id!==next.id)return [];return selected;}
function template(f){return S.templates[f.template_id].replace(/\{([a-z]+)\}/g,(_,key)=>String(key==='season'?f.season:(f.values||{})[key]??''));}
function receiptSet(cards){const cap=Math.max(1,Math.ceil(cards.length*R.leading_share)),counts={},map={};cards.forEach(c=>{const pair=angles(c);if(pair.length&&(counts[pair[0].class_id]||0)<cap){map[c.id]=pair;counts[pair[0].class_id]=(counts[pair[0].class_id]||0)+1;}else map[c.id]=[];});return map;}
function rung(c){const d=draft(c);return c.ladder.find(r=>r.line===d.line&&r.side===c.side&&r.valid_side===true&&Number.isFinite(r.p_at_line)&&r.p_at_line>=0&&r.p_at_line<=1&&Number.isFinite(r.p_fair)&&breakEven(r.worth_odds)!==null)||null;}
function verdict(c){const d=draft(c),r=rung(c),be=breakEven(d.odds);if(!r)return {valid:false,text:'Outside this sample ladder. Choose a supported line.'};if(be===null)return {valid:false,text:'Enter American odds of +100 or higher, or -100 or lower.'};if(!d.touched){return {valid:true,good:r.p_at_line>r.p_fair,text:r.p_at_line>r.p_fair?'Worth it at '+signed(r.worth_odds)+' or better':'Priced fair — no lean either way.'};}const good=r.p_at_line>be;return {valid:true,good,text:good?'Still good at '+signed(Number(d.odds))+' and '+d.line:'Not at '+signed(Number(d.odds))+' — pass'};}
function snapshotLeg(c){const r=rung(c),d=draft(c);return {forecast_source:{kind:"edge",card_id:c.id},player_id:c.player_id,player:c.player,team:c.team,market:c.market,side:c.side,line:d.line,odds:Number(d.odds),p_at_line:r.p_at_line};}
function take(key,payload){if(state.keys[key])return decision(state.keys[key]);const id='decision-'+(state.decisions.length+1),data=copy(payload);data.legs=(data.legs||[]).map(l=>Object.freeze(l));const d=Object.assign(data,{id,taken_at:new Date().toISOString(),placement:'unconfirmed',angle:null,reasonComplete:!state.askWhy,done:false});Object.freeze(d.legs);state.decisions.push(d);state.keys[key]=id;return d;}
function external(key,payload){return take(key,Object.assign({source:'Manual builder',kind:payload.legs.length>1?'parlay':'single'},payload));}
function prompt(id){const d=decision(id);if(!d)return '';if(d.done)return '<p class="ef-taken">Saved in My bets</p>'+(d.angle?'<p class="ef-saved-angle">Your angle: '+esc(d.angle)+'</p><small>Personal note · ungraded</small>':'');return '<section class="ef-decision" data-decision="'+id+'"><p class="ef-taken">Recorded · placement unconfirmed</p>'+(d.reasonComplete?(d.angle?'<p class="ef-saved-angle">Your angle: '+esc(d.angle)+'</p><small>Personal note · ungraded</small>':''):'<label for="ef-reason-'+id+'">What is your angle? <span>(optional)</span></label><textarea id="ef-reason-'+id+'" data-ef-field="reason" data-id="'+id+'" rows="2" maxlength="1000" placeholder="Explain why you think this player might go over or under their stated line.">'+esc(state.reasonDrafts[id]||'')+'</textarea><div class="ef-inline-actions">'+button('reason-save','Save',id)+button('reason-skip','Skip',id)+'</div>')+button('done','Done',id,' class="ef-done"')+'</section>';}
function ownedId(l){return l.player_id||F.identity_map[l.player]||null;}
function owned(player){return state.decisions.some(d=>d.legs.some(l=>ownedId(l)===player));}
function strip(surface,roster){const items=surface==='bets'?state.decisions.map(d=>({label:d.legs[0].player+(d.legs.length>1?' + '+(d.legs.length-1):''),id:d.id,state:'Recorded'})):(roster||[]).map(p=>({label:p.name,id:p.player_id,state:'On your lineup',lineup:true}));if(!items.length)return '';return '<aside class="ef-owned-strip" aria-label="'+(surface==='bets'?'Your recorded bets':'Your sample lineup')+'">'+items.slice(0,state.ownedExpanded?items.length:2).map(i=>button(i.lineup?'lineup':'detail','<span>'+esc(i.label)+'</span><small>'+i.state+'</small>',i.id)).join('')+(items.length>2?button('owned-more',state.ownedExpanded?'Less':'+'+(items.length-2),null,' aria-expanded="'+state.ownedExpanded+'"'):'')+'</aside>';}
function assessment(c){return blind(c)?'Limited evidence':c.calibration_status!=='sample-checked'?'Unverified estimate':gap(c)<=0?'No model advantage':bolts(c)<=2?'Small model advantage':'Model above market';}
function assessmentHtml(c){return '<span class="ef-assessment'+(blind(c)?' is-limited':'')+'">'+assessment(c)+'</span>';}
function offerCandidates(c){
 const d=draft(c),taken=d.take&&decision(d.take),base=taken?taken.legs[0]:(verdict(c).valid?snapshotLeg(c):null);if(!base)return [];
 return c.riders.filter(r=>r.base_line===base.line&&r.base_side===base.side&&Number.isFinite(r.p_joint)&&r.p_joint>=0&&r.p_joint<=1&&r.p_joint===r.p_product&&r.legs.length>0&&r.legs.every(l=>Number.isFinite(l.p_at_line)&&l.p_at_line>=0&&l.p_at_line<=1&&Number.isFinite(l.line)&&['Over','Under'].includes(l.side)&&breakEven(l.odds)!==null)&&r.receipts.length===r.legs.length&&r.receipts.every(x=>x.class_id==='pairwise-co-hit'&&Number.isInteger(x.n)&&x.n>=R.n_floor&&Number.isInteger(x.hits)&&x.hits>=0&&x.hits<=x.n&&[2023,2024].includes(x.season)&&!/pff|home.away/i.test(x.source))).map(r=>{
   const legs=[base].concat(r.legs),price=exactPrice(legs),total=payout(legs,10);if(!price||total===null||price.p_joint!==r.p_joint||price.p_product!==r.p_product)return null;
   return {candidate:r,legs,price,total,required:10/total,key:JSON.stringify([r.id,legs])};
 }).filter(Boolean).sort((a,b)=>(b.price.p_joint-b.required)-(a.price.p_joint-a.required)||c.riders.indexOf(a.candidate)-c.riders.indexOf(b.candidate));
}
function riderOffer(c){return offerCandidates(c)[0]||null;}
function offerTerms(c){const o=riderOffer(c);return button('generate','Generate best parlay',c.id,' class="ef-generate"'+(!o?' disabled':''))+(!o?'<p class="ef-caption">Sample parlay unavailable for these terms.</p>':'');}
function riderHtml(c,offer){if(!offer)return '';const saved=state.offerTakes[offer.key];return '<section class="ef-riders">'+offer.legs.map(l=>'<p>'+esc(l.player+' · '+l.side+' '+l.line+' '+l.market)+' · '+esc(signed(l.odds))+'</p>').join('')+window.OutlookHistory.combination(offer.legs,offer.price.p_joint)+window.OutlookHistory.differential(offer.required,offer.price.p_joint)+'<details class="ef-saved-history"><summary id="ef-offer-history-toggle">Show past results</summary>'+window.OutlookHistory.matrix(offer.legs)+'</details>'+'<p class="ef-caption">$10 example return: $'+offer.total.toFixed(2)+' · includes stake</p>'+reminder()+(saved?prompt(saved):'')+'<div class="ef-offer-actions">'+(saved?'':button('rider-save','Save parlay',c.id,' class="ef-primary"'))+button('customize','Customize legs',c.id,' class="ef-customize"')+'</div>'+'</section>';}
function sheetOffer(c){return state.offerSheet&&state.offerSheet.card===c.id?state.offerSheet.offer:null;}
function sheetMarkup(){const sheet=state.offerSheet,c=sheet&&byId(sheet.card);return c?'<div class="ef-offer-backdrop" data-act="ef-offer-close" aria-hidden="true"></div><section class="ef-offer-sheet" role="dialog" aria-modal="true" aria-labelledby="ef-offer-title" tabindex="-1"><header><h2 id="ef-offer-title">Best available sample parlay</h2>'+button('offer-close','Close',null,' aria-label="Close best parlay"')+'</header><div class="ef-offer-scroll">'+riderHtml(c,sheet.offer)+'</div></section>':'';}
function openOffer(c){const offer=riderOffer(c);if(!offer)return;if(observer)observer.disconnect();observer=null;const viewport=document.getElementById('viewport'),card=document.querySelector&&document.querySelector('[data-card="'+c.id+'"]');if(viewport&&card&&card.getBoundingClientRect){const y=card.getBoundingClientRect().top-viewport.getBoundingClientRect().top+viewport.scrollTop;viewport.scrollTop=y;}state.offerSheet={card:c.id,offer:copy(offer)};syncSheet();}
function closeOffer(restore=true){const card=state.offerSheet&&state.offerSheet.card;state.offerSheet=null;const portal=document.getElementById('ef-offer-overlay');if(portal){portal.hidden=true;portal.innerHTML='';}if(sheetLock){sheetLock.nodes.forEach(x=>{x.node.inert=x.inert;});if(sheetLock.viewport)sheetLock.viewport.style.overflow=sheetLock.overflow;if(document.body)document.body.style.overflow=sheetLock.bodyOverflow;sheetLock=null;}if(restore&&card&&document.querySelector){const target=document.querySelector('[data-act="ef-generate"][data-value="'+card+'"]');if(target)target.focus({preventScroll:true});}if(restore&&host.route()==='screen')sync('screen');}
function syncSheet(){if(!state.offerSheet)return;const portal=document.getElementById('ef-offer-overlay');if(!portal)return;const fresh=portal.hidden,active=document.activeElement,held=active&&portal.contains(active),act=held&&active.getAttribute('data-act'),value=held&&active.getAttribute('data-value'),id=held&&active.id,scroll=portal.querySelector('.ef-offer-scroll'),top=scroll?scroll.scrollTop:0,history=portal.querySelector('.ef-saved-history'),historyOpen=history&&history.open,markup=sheetMarkup();
if(!sheetLock){const viewport=document.getElementById('viewport'),app=document.getElementById('app'),nodes=app?Array.from(app.children).filter(n=>n!==portal).map(node=>({node,inert:node.inert})):[];sheetLock={nodes,viewport,overflow:viewport?viewport.style.overflow:'',bodyOverflow:document.body?document.body.style.overflow:''};nodes.forEach(x=>{x.node.inert=true;});if(viewport)viewport.style.overflow='hidden';if(document.body)document.body.style.overflow='hidden';}
portal.hidden=false;if(portal.innerHTML!==markup)portal.innerHTML=markup;const restoredHistory=portal.querySelector('.ef-saved-history');if(restoredHistory&&historyOpen)restoredHistory.open=true;const updated=portal.querySelector('.ef-offer-scroll');if(updated)updated.scrollTop=top;const controls=Array.from(portal.querySelectorAll('button:not(:disabled),textarea,input,select,a[href],summary'));if(fresh){const target=controls[0]||portal.querySelector('[role="dialog"]');if(target)target.focus({preventScroll:true});}else if(held){const target=(id&&document.getElementById(id))||controls.find(n=>n.getAttribute('data-act')===act&&n.getAttribute('data-value')===value)||portal.querySelector('textarea')||controls[0];if(target)target.focus({preventScroll:true});}}
function sheetKey(event){if(!state.offerSheet)return false;if(event.key==='Escape'){event.preventDefault();closeOffer();return true;}if(event.key==='Tab'){const portal=document.getElementById('ef-offer-overlay'),controls=portal&&Array.from(portal.querySelectorAll('button:not(:disabled),textarea,input,select,a[href],summary'));if(controls&&controls.length){const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&(document.activeElement===first||!portal.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||!portal.contains(document.activeElement))){event.preventDefault();first.focus();}}return true;}return false;}
function openBody(c,pair){const d=draft(c),v=verdict(c),r=rung(c);if(d.take)return prompt(d.take)+historyChart(decision(d.take).legs[0],c.id)+offerTerms(c);return '<section class="ef-opportunity-conclusion"><span>At your selected line</span><strong>'+esc(v.text)+'</strong><p>'+pct(r?r.p_at_line:null)+' estimated chance · '+esc(c.side+' '+d.line+' '+c.market)+'</p></section><div class="ef-angles"><h3>Angles</h3>'+(pair.length?pair.map(f=>'<p class="ef-receipt">'+esc(template(f))+'</p>').join(''):'<p>'+esc(gap(c)>0&&angles(c).length?S.unavailable:S.fallback)+'</p>')+'<details class="ef-provenance"><summary>Sample sources</summary>'+pair.map(f=>'<p>'+esc(f.source+' · '+(f.season||'current snapshot')+(f.historical?' · '+f.n+' observations':''))+'</p>').join('')+'<p>Fictional context, not separate probability boosts.</p></details></div>'+(blind(c)?'<p class="ef-caption">Blind-spot example · a large gap can reflect model limits.</p>':'')+historyChart({player:c.player,market:c.market,side:c.side,line:d.line,odds:d.odds,p_at_line:r?r.p_at_line:null},c.id)+'<div class="ef-edit"><div><label>Your line</label><div class="ef-stepper">'+button('step','−',c.id,' data-delta="-0.5" aria-label="Lower line"')+'<strong>'+d.line+'</strong>'+button('step','+',c.id,' data-delta="0.5" aria-label="Raise line"')+'</div></div><div><label for="ef-odds-'+c.id+'">Your odds</label><input id="ef-odds-'+c.id+'" aria-invalid="'+(breakEven(d.odds)===null)+'" aria-describedby="ef-verdict-'+c.id+'" data-ef-field="odds" data-id="'+c.id+'" inputmode="decimal" value="'+esc(d.odds)+'"></div></div><p id="ef-verdict-'+c.id+'" class="ef-verdict '+(v.good?'positive':'')+'"'+(!v.valid?' role="status"':'')+'>'+esc(v.text)+'</p><p class="ef-caption">'+(r?'Chance at your line: '+pct(r.p_at_line):'No chance available')+' · '+esc(c.side+' '+c.market)+'</p>'+button('take','Record bet',c.id,' class="ef-primary"'+(!v.valid?' disabled':''))+reminder()+offerTerms(c);}
function cardHtml(c,pair,isHero){const d=draft(c),open=state.open===c.id,taken=d.take&&decision(d.take),shown=taken?taken.legs[0]:c,rating=taken?Object.assign({},c,{p_at_line:shown.p_at_line,p_fair:(rung(c)||c).p_fair}):c;return '<article class="ef-card'+(isHero?' ef-hero':'')+(isHero&&state.pulse&&!host.reduced()?' ef-entry':'')+'" data-card="'+c.id+'">'+(isHero?'<div class="ef-hero-label">'+(taken?'Your recorded bet':'Tonight’s best bet')+'</div>':'')+'<button class="ef-card-toggle" data-act="ef-open" data-value="'+c.id+'" aria-expanded="'+open+'" aria-controls="ef-body-'+c.id+'"><span class="ef-card-name">'+esc(c.name)+(d.take?'<small>Recorded · your line</small>':'')+'</span><span class="ef-card-line">'+esc(shown.side+' '+shown.line+' '+shown.market)+'</span><span class="ef-card-rating">'+assessmentHtml(rating)+'<span class="ef-card-chance"><strong>'+pct(shown.p_at_line)+'</strong><small>Estimated chance</small></span></span><span class="ef-market-context"><span>'+esc(c.team+' · '+c.opponent+' · '+c.time)+'</span><b>'+esc(signed(shown.odds))+' odds</b></span></button><div class="ef-card-body" id="ef-body-'+c.id+'"'+(open?'':' hidden')+'>'+ (open?openBody(c,pair):'')+'</div></article>';}
function render(){const list=visible(),best=hero(),h=best&&list.find(c=>c.id===best.id),ordered=h?[h].concat(list.filter(c=>c.id!==h.id)):list,pairs=receiptSet(ordered),all=filtered(),graded=F.graded.filter(r=>r.status==='graded');const html='<div class="page ef-page"><header class="ef-header"><div><h1>Edge Finder</h1><p class="ef-sample">'+F.sample+'</p></div>'+button('mybets','My bets · '+state.decisions.length)+'</header>'+strip('bets')+'<nav class="ef-discovery" aria-label="Bet discovery"><span aria-current="page">Singles</span>'+button('recommended','Parlays')+'</nav><div class="ef-search"><label class="sr-only" for="ef-search">Search players or teams</label><input id="ef-search" data-ef-field="search" placeholder="Search players or teams" value="'+esc(state.query)+'">'+(state.query?button('clear','Clear'):'')+'</div><div class="ef-filters" aria-label="Discovery filters">'+[['all','All'],['tonight','Tonight'],['safe','Safe'],['long','Long shots']].map(x=>button('filter',x[1],x[0],' aria-pressed="'+(state.filter===x[0])+'"')).join('')+'</div>'+(state.filter==='safe'?'<p class="ef-caption">65% or higher sample chance · never guaranteed</p>':'')+(graded.length?'<p class="ef-trust">Demo record: '+graded.filter(r=>r.won).length+' of '+graded.length+' sample bets won</p>':'')+'<div id="ef-feed">'+ordered.map(c=>cardHtml(c,pairs[c.id],h&&c.id===h.id)).join('')+'</div>'+(all.length?list.length<all.length?'<div class="ef-more-sentinel">'+button('more','Show more')+'</div>':'<p class="ef-end">All '+all.length+' matching sample lines shown.</p>':'<p class="ef-end">No matching sample lines. Try another player or team.</p>')+'<label class="ef-setting"><input type="checkbox" data-ef-field="ask"'+(state.askWhy?' checked':'')+'> Ask for my angle when I record a bet</label></div>';state.pulse=false;return html;}
function refresh(focusId){const active=document.activeElement,act=active&&active.getAttribute&&active.getAttribute('data-act'),value=active&&active.getAttribute&&active.getAttribute('data-value'),delta=active&&active.getAttribute&&active.getAttribute('data-delta'),start=active&&active.selectionStart,end=active&&active.selectionEnd,id=focusId||(active&&active.id),scroll=document.getElementById('viewport'),top=scroll&&scroll.scrollTop;host.render();if(state.offerSheet)return;const node=id&&document.getElementById(id);if(node){node.focus({preventScroll:true});if(start!=null&&node.setSelectionRange)node.setSelectionRange(start,end);}else if(act&&document.querySelectorAll){const match=Array.from(document.querySelectorAll('[data-act]')).find(n=>n.getAttribute('data-act')===act&&n.getAttribute('data-value')===value&&n.getAttribute('data-delta')===delta);if(match)match.focus({preventScroll:true});else {const fallback=document.getElementById('ef-search');if(fallback)fallback.focus({preventScroll:true});}}if(scroll)scroll.scrollTop=top;}
function input(field,value,id){if(field==='search'){state.query=String(value);state.limit=R.batch;}else if(field==='odds'){const c=byId(id);if(!c||draft(c).take)return;draft(c).odds=String(value);draft(c).touched=true;}else if(field==='reason'){if(!decision(id)||decision(id).reasonComplete)return;state.reasonDrafts[id]=String(value).slice(0,1000);return;}else if(field==='ask'){state.askWhy=!!value;if(!state.askWhy)state.decisions.forEach(d=>{d.reasonComplete=true;});}else return;state.pulse=false;refresh();}
function action(act,value,delta){if(act==='browse'){if(host.browse)host.browse();return;}state.pulse=false;const c=byId(value);if(act==='generate'&&c){openOffer(c);return;}else if(act==='offer-close'){closeOffer();return;}else if(act==='history-mode'){const parts=String(value).split('|');state.historyMode[parts[0]]=parts[1]==='past'?'past':'current';}else if(act==='history-level'||act==='history-season'){const parts=String(value).split('|'),view=state.historyViews[parts[0]]||(state.historyViews[parts[0]]={level:'recent',season:2025});if(act==='history-season'&&[2023,2024,2025].includes(Number(parts[1]))){view.season=Number(parts[1]);view.level='season';}else if(['annual','recent'].includes(parts[1]))view.level=parts[1];}else if(act==='open'&&c)state.open=state.open===value?null:value;else if(act==='filter'&&['all','tonight','safe','long'].includes(value)){state.filter=value;state.limit=R.batch;}else if(act==='clear'){state.query='';state.limit=R.batch;}else if(act==='more')state.limit=Math.min(state.limit+R.batch,filtered().length);else if(act==='step'&&c&&!draft(c).take&&[-.5,.5].includes(Number(delta))){draft(c).line+=Number(delta);draft(c).touched=true;}else if(act==='take'&&c&&verdict(c).valid){const d=draft(c);d.take=take('feed:'+c.id,{source:'Edge Finder',kind:'single',card_id:c.id,legs:[snapshotLeg(c)]}).id;state.open=c.id;}else if(act==='reason-save'||act==='reason-skip'){const d=decision(value);if(!d||d.reasonComplete)return;d.angle=act==='reason-save'?(state.reasonDrafts[value]||'').trim()||null:null;d.reasonComplete=true;}else if(act==='done'){const d=decision(value);if(!d)return;d.reasonComplete=true;d.done=true;}
else if(act==='customize'&&c){const o=sheetOffer(c)||riderOffer(c);if(!o)return;const legs=copy(o.legs);closeOffer(false);host.customize(legs);return;}
else if(act==='rider-save'&&c){const o=sheetOffer(c)||riderOffer(c);if(!o)return;state.offerTakes[o.key]=take('rider:'+o.key,{source:'Edge Finder parlay',kind:'parlay',legs:o.legs,p_joint:o.price.p_joint,p_product:o.price.p_product,trace:o.price.trace}).id;}
else if(act==='mybets'){host.mybets();return;}else if(act==='recommended'){host.recommended();return;}else if(act==='lineup'){host.lineup();return;}else if(act==='history'){host.history();return;}else if(act==='detail'&&decision(value)){state.selected=value;host.detail();return;}else if(act==='detail-ladder'&&decision(value))state.detailLadders[value]=!state.detailLadders[value];else if(act==='owned-more')state.ownedExpanded=!state.ownedExpanded;else return;refresh();}
function cleanup(capture){if(capture!==false&&document.querySelectorAll)Array.from(document.querySelectorAll('[id^=ef-ladder-]')).forEach(n=>{if(n.id)state.detailScroll[n.id]=n.scrollTop;});if(observer)observer.disconnect();observer=null;}
function sync(route){if(route!=='screen'&&state.offerSheet)closeOffer(false);if(state.offerSheet){if(observer)observer.disconnect();observer=null;syncSheet();return;}if(observer)observer.disconnect();observer=null;Object.keys(state.detailScroll).forEach(id=>{const node=document.getElementById(id);if(node)node.scrollTop=state.detailScroll[id];});if(route!=='screen'||!window.IntersectionObserver)return;const sentinel=document.querySelector&&document.querySelector('.ef-more-sentinel'),viewport=document.getElementById('viewport');if(!sentinel||!viewport)return;const watching=new window.IntersectionObserver(entries=>{if(state.offerSheet||observer!==watching||!sentinel.isConnected||host.route()!=='screen')return;if(entries.some(e=>e.isIntersecting)&&viewport.scrollTop>0){cleanup();action('more');}},{root:viewport});observer=watching;watching.observe(sentinel);}
function mybets(){return '<div class="page ef-page">'+host.head('My bets')+(host.recordEntry?host.recordEntry():'')+'<p class="ef-sample">Demo · taken decisions · this visit only</p>'+reminder()+(state.decisions.length?state.decisions.map(d=>'<article class="ef-owned-card"><span class="ef-caption">'+esc(d.source)+' · Recorded · placement unconfirmed</span><h2>'+esc(d.legs.map(l=>l.player).join(' + '))+'</h2><p>'+esc(d.legs.length===1?d.legs[0].side+' '+d.legs[0].line+' '+d.legs[0].market:d.legs.length+' bets together')+'</p>'+button('detail','View bet',d.id)+'</article>').join(''):'<section class="ef-empty"><h2>Your picks start here</h2><p>Explore a player or build a bet to keep it here for this visit.</p>'+button('browse','Browse Bets',null,' class="ef-primary"')+'</section>')+'<p class="ef-caption">Your separate Home history example</p>'+button('history','Renner sample bet history')+'</div>';}
function savedLadder(d){
 const c=byId(d.card_id),leg=d.legs[0];if(!c||c.player_id!==leg.player_id||c.market!==leg.market||c.side!==leg.side)return '';
 const rows=c.ladder.filter(r=>r.side===leg.side&&r.valid_side),at=rows.findIndex(r=>r.line===leg.line);if(at<0)return '<p>Pre-game ladder unavailable.</p>';
 const full=!!state.detailLadders[d.id],shown=full?rows:rows.slice(Math.max(0,at-1),at+2),id='ef-ladder-'+d.id;
 return '<section class="bb-single-ladder"><h2>Pre-game chances</h2><div class="bb-single-rows'+(full?' is-expanded':'')+'" id="'+id+'">'+shown.map(r=>'<div class="bb-single-rung'+(r.line===leg.line?' is-selected':'')+'"><span>'+esc(leg.side+' '+r.line+' '+leg.market)+(r.line===leg.line?'<small>Your line</small>':'')+'</span><strong>'+pct(r.line===leg.line?leg.p_at_line:r.p_at_line)+'</strong></div>').join('')+'</div>'+button('detail-ladder',full?'Show less':'Show full ladder',d.id,' aria-expanded="'+full+'" aria-controls="'+id+'"')+'</section>';
}
function detail(){const d=decision(state.selected);if(!d)return '<div class="page">'+host.head('My bet')+'<p>Select a taken bet from My bets.</p></div>';const single=d.kind==='single'&&d.totals&&host.singleDetail;return '<div class="page ef-page">'+host.head('My bet')+'<p class="ef-sample">Demo · '+esc(d.source)+' · this visit only</p><p class="ef-taken">Recorded · placement unconfirmed</p>'+(single?host.singleDetail(d):d.legs.map(l=>'<div class="ef-owned-card"><h2>'+esc(l.player)+'</h2><p>'+esc(l.side+' '+l.line+' '+l.market)+(l.odds==null?'':' · '+esc(signed(l.odds)))+'</p><strong>'+pct(l.p_at_line)+' sample chance</strong></div>').join('')+(d.kind==='single'?savedLadder(d):'')+(d.kind==='parlay'&&Number.isFinite(d.p_joint)?'<p>'+pct(d.p_joint)+' combined · assumes each bet is independent</p>':''))+(!single&&(Number.isFinite(d.stake)||d.totals)?'<div class="bb-totals"><div><span>Stake</span><strong>$'+Number(d.stake).toFixed(2)+'</strong></div><div><span>Return if won · includes stake</span><strong>'+((d.totals&&Number.isFinite(d.totals.total))?'$'+d.totals.total.toFixed(2):Number.isFinite(d.return_total)?'$'+d.return_total.toFixed(2):'Unavailable')+'</strong></div></div>':'')+(Number.isFinite(d.payout_multiple)?'<p>Entered payout: '+d.payout_multiple+' times stake</p>':'')+reminder()+prompt(d.id)+'</div>';}
window.EdgeFinder={configure:api=>{host=api;},exactPrice,historyKey,historyChart,sheetMarkup,sheetKey,closeOffer,offerCandidates,riderOffer,state,assessment,bolts,blind,gap,filtered,visible,hero,angles,receiptSet,template,verdict,rung,render,action,input,take,external,prompt,strip,owned,ownedId,mybets,detail,sync,cleanup,breakEven,payout};
}());
