/* Fixture-only DFS: every outcome and lineup is supplied, never simulated here. */
(function(){
'use strict';
let host={},f={};
const state={picked:[],weights:{},count:5,choices:['0','0'],expanded:null,text:'',confirm:false,savedStories:[],savedLineups:[],expandedLineup:null};
const e=x=>host.esc?host.esc(x):String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,act,value='',cls='',disabled=false)=>'<button class="fdfs-button '+cls+'" data-act="fdfs-'+act+'" data-value="'+e(value)+'"'+(disabled?' disabled':'')+'>'+label+'</button>';
const player=id=>f.players[id];
const story=id=>f.stories.find(s=>s.id===id);
const percent=x=>x==null?'Not supplied':e(x)+'%';
const disc=(lines,label)=>host.disclosure(lines,label||'How to read this');
const go=page=>host.open(page);
const refresh=()=>{const active=typeof document!=='undefined'?document.activeElement:null,id=active&&active.id,act=active&&active.dataset&&active.dataset.act,value=active&&active.dataset&&active.dataset.value;host.render();let next=id&&document.getElementById?document.getElementById(id):null;if(!next&&act&&document.querySelectorAll)next=Array.from(document.querySelectorAll('[data-act]')).find(el=>el.dataset.act===act&&el.dataset.value===value);if(next)next.focus({preventScroll:true});};
function configure(h){host=h;f=h.fixture;if(window.FantasyDfsTournament)window.FantasyDfsTournament.configure(h);}
function profile(){const key=state.picked.slice().sort().map(id=>id+':'+(state.weights[id]||0)).join('|')+'@'+state.count;return f.allocation_profiles[key]||null;}
function chosenLineups(){const p=profile();return p?(p.variants[state.choices.join(':')]||[]).map(id=>f.lineups[id]):[];}
function summaryPlayer(id){const p=player(id);return '<div class="fdfs-person"><strong>'+e(p.player_name)+'</strong><small>'+e(p.team)+' · '+e(p.position)+'</small>'+host.statline(p.statline)+'</div>';}
function shell(page,title,content){return '<section class="fdfs"><div class="fdfs-top"><span class="fdfs-demo">Demo · fictional numbers</span>'+(page==='dfs'?'':btn('Back','back'))+'</div><h2>'+e(title)+'</h2>'+content+'</section>';}
function board(){return '<p class="fdfs-muted">'+e(f.slate)+' · DraftKings tournaments</p>'+f.cards.map(c=>'<article class="fdfs-card"><button class="fdfs-card-toggle" data-act="fdfs-expand" data-value="'+c.id+'" aria-expanded="'+(state.expanded===c.id)+'"><small>'+e(c.kind)+'</small><strong>'+e(c.title)+'</strong><span>'+e(c.summary)+'</span>'+(c.graded?'<b class="fdfs-grade">✓ '+e(c.graded)+'</b>':'')+'</button>'+(state.expanded===c.id?'<div class="fdfs-details">'+c.evidence.map(x=>'<p>'+e(x)+'</p>').join('')+c.player_ids.map(summaryPlayer).join('')+(c.story_id?btn('Build around this story','from-card',c.story_id,'primary'):'')+'</div>':'')+'</article>').join('')+btn('Build around a story','open','stories','primary')+disc([host.legacy?host.legacy():''],'Slate tables')+'<p class="fdfs-record">'+e(f.record)+'</p>';}
function map(){return '<div class="fdfs-map" aria-label="Story map: more likely at the top, more crowded to the right"><span class="fdfs-map-top">More likely</span><span class="fdfs-map-side">More crowded →</span>'+f.stories.filter(s=>s.likely!=null).map(s=>'<button aria-label="'+e(s.title)+': '+percent(s.likely)+' likely, '+percent(s.crowd)+' crowded" style="left:'+Math.min(87,12+s.crowd*1.8)+'%;bottom:'+Math.min(80,s.likely)+'%" data-act="fdfs-pick" data-value="'+s.id+'" aria-pressed="'+state.picked.includes(s.id)+'">'+s.id.slice(1)+'</button>').join('')+'</div><small class="fdfs-muted">The injury story has no likelihood estimate and is left off the map.</small>';}
function storyList(){return (state.savedStories.length?'<p class="fdfs-record">Saved for this visit: '+state.savedStories.map(e).join(' · ')+'</p>':'')+map()+f.stories.map((s,i)=>'<article class="fdfs-card fdfs-story"><div class="fdfs-story-title"><strong>'+(i+1)+'. '+e(s.title)+'</strong>'+btn(state.picked.includes(s.id)?'Picked ✓':'Pick','pick',s.id,state.picked.includes(s.id)?'selected':'')+'</div><p class="fdfs-muted">'+s.players.map(id=>e(player(id).player_name)).join(' · ')+'</p><div class="fdfs-three"><span>Likely<b>'+percent(s.likely)+'</b></span><span>Top-week chance<b>'+percent(s.payoff.chance)+'</b><small>'+e(player(s.payoff.player_id).player_name)+'</small></span><span>Players together<b>'+percent(s.crowd)+'</b><small>Projected ownership</small></span></div><p class="fdfs-story-effect">'+(s.moves_numbers?'Changes your sample numbers':e(s.tested_text))+'</p><small>'+percent(s.app_crowd_share)+' of Angles sample lineups use this story.</small>'+disc(s.evidence.concat(s.moves_numbers?s.numbers.map(n=>player(n.player_id).player_name+' · Baseline '+n.baseline+' → Your number '+n.yours):[]).concat(['Top-week chance belongs to the named player, not the whole lineup.']),'The evidence')+'</article>').join('')+btn('Write your own','open','story-read')+btn('Split your belief · '+state.picked.length+' picked','open','beliefs','primary',state.picked.length<2||state.picked.length>5);}
function read(){return '<div class="fdfs-read-steps"><b>'+(state.confirm?'Say it':'SAY IT')+'</b> · '+(state.confirm?'CONFIRM':'Confirm')+'</div>'+(!state.confirm?'<label for="fdfs-reason">What do you think happens?</label><textarea id="fdfs-reason" data-fdfs-field="text" placeholder="Tell your story for this slate">'+e(state.text)+'</textarea>'+btn('Try the Chiefs–Bills example','example')+btn('Review story','review','','primary',!state.text.trim()):'<div class="fdfs-card"><strong>What we heard</strong><p>'+e(state.text)+'</p><p>'+e(state.text===f.stories[0].title?f.stories[0].tested_text:"Saved and graded after the slate; we can't size this kind of story yet.")+'</p>'+ (state.text===f.stories[0].title?f.stories[0].numbers.map(n=>'<p>'+e(player(n.player_id).player_name)+' · Baseline '+e(n.baseline)+' → Your number <strong>'+e(n.yours)+'</strong></p>').join(''):'<p>Your numbers stay unchanged. This typed story has no sample-tested effect.</p>')+'</div>'+btn('Edit','edit')+btn('Save sample story','save-story','','primary'))+'<p class="fdfs-muted">Sample interpretation · saved for this visit only.</p>';}
function beliefs(){const total=state.picked.reduce((n,id)=>n+(state.weights[id]||0),0),p=profile();return '<label for="fdfs-count">How many lineups?</label><select id="fdfs-count" data-fdfs-field="count">'+[5,10,25].map(n=>'<option '+(state.count===n?'selected':'')+'>'+n+'</option>').join('')+'</select>'+state.picked.map(id=>'<div class="fdfs-card"><label for="fdfs-weight-'+id+'">'+e(story(id).title)+' <b>'+(state.weights[id]||0)+'%</b></label><input id="fdfs-weight-'+id+'" type="range" min="0" max="100" step="20" value="'+(state.weights[id]||0)+'" data-fdfs-field="weight" data-fdfs-id="'+id+'"><small>'+(p?p.allocations.find(x=>x.story_id===id).count+' of '+state.count+' lineups':'Set the total to 100% to see the split')+'</small></div>').join('')+'<div class="fdfs-total">Total <strong>'+total+'%</strong></div><p class="fdfs-muted">Move each slider in 20% steps. Your choices stay exactly as set.</p>'+btn('Choose the close calls','open','close-calls','primary',total!==100||!p);}
function calls(){return f.close_calls.map((q,qi)=>'<fieldset class="fdfs-calls"><legend>'+e(q.title)+'</legend>'+q.options.map(o=>{const p=player(o.player_id);return '<button aria-pressed="'+(state.choices[qi]===o.id)+'" class="fdfs-option '+(state.choices[qi]===o.id?'selected':'')+'" data-act="fdfs-choice" data-value="'+qi+':'+o.id+'"><small>'+e(o.label)+'</small><strong>'+e(p.player_name)+'</strong><span>'+e(p.proj)+' projected points · '+percent(p.ownership)+' ownership</span></button>';}).join('')+'</fieldset>').join('')+btn('See your '+state.count+' lineups','open','lineups','primary',!profile());}
function lineups(){const rows=chosenLineups();if(!rows.length)return '<p>Pick stories and set your belief split first.</p>'+btn('Choose stories','open','stories');return '<p class="fdfs-muted">'+rows.length+' sample lineups · '+e(f.record)+'</p>'+rows.map((l,i)=>'<article class="fdfs-card"><button class="fdfs-card-toggle" data-act="fdfs-lineup" data-value="'+e(l.id)+'" aria-expanded="'+(state.expandedLineup===l.id)+'"><small>Lineup '+(i+1)+' · $'+e(l.salary)+'</small><strong>'+e(story(l.story_id).title)+'</strong><span>'+e(l.projected_points)+' projected points</span></button><div class="fdfs-details"><p>'+e(l.why)+'</p><div class="fdfs-meter"><span>Identical-entry chance</span><strong>'+percent(l.uniqueness.duplicate_chance)+'</strong><meter min="0" max="100" value="'+l.uniqueness.duplicate_chance+'" aria-label="Identical-entry chance"></meter></div>'+disc([l.uniqueness.definition,'Each sample lineup differs from another by at least two players.'])+'<small>'+percent(l.app_crowd_share)+' of Angles sample lineups use this story.</small>'+(state.expandedLineup===l.id?'<div class="fdfs-roster">'+l.slots.map(p=>'<div><small>'+e(p.slot)+'</small><span>'+e(p.player_name)+'<small>'+e(p.team)+' · $'+e(p.salary)+'</small></span><b>'+e(p.proj)+'</b></div>').join('')+'</div>':'')+btn(state.savedLineups.includes(l.id)?'Saved ✓':'Save to My lineup','save-lineup',l.id,'primary',state.savedLineups.includes(l.id))+'</div></article>').join('')||'<p>Pick stories and set your belief split first.</p>'+btn('Choose stories','open','stories');}
function renderLegacy(page){const screens={dfs:['This slate',board],stories:['Build around a story',storyList],'story-read':['Your story',read],beliefs:['Your belief split',beliefs],'close-calls':['Make it yours',calls],lineups:['Your lineups',lineups]};const x=screens[page]||screens.dfs;return shell(page,x[0],x[1]());}
function action(act,value){if(window.FantasyDfsTournament&&act.startsWith('fdfs-t-'))return window.FantasyDfsTournament.action(act,value);if(!act.startsWith('fdfs-'))return false;act=act.slice(5);if(act==='back'){host.back();return true;}if(act==='open'){if(['close-calls','lineups'].includes(value)&&!profile()){go('beliefs');return true;}if(value==='beliefs'&&state.picked.length<2){go('stories');return true;}if(value==='story-read')state.confirm=false;go(value);return true;}if(act==='expand')state.expanded=state.expanded===value?null:value;else if(act==='pick'){if(state.picked.includes(value))state.picked=state.picked.filter(id=>id!==value);else if(story(value)&&state.picked.length<5){state.picked.push(value);state.weights[value]=0;}}else if(act==='from-card'){if(!state.picked.includes(value)){state.picked.push(value);state.weights[value]=0;}go('stories');return true;}else if(act==='example')state.text=f.stories[0].title;else if(act==='review')state.confirm=!!state.text.trim();else if(act==='edit')state.confirm=false;else if(act==='save-story'){if(state.text===f.stories[0].title&&!state.picked.includes('s1')){state.picked.push('s1');state.weights.s1=0;}state.savedStories.push(state.text);state.confirm=false;go('stories');return true;}else if(act==='choice'){const parts=value.split(':');if(f.close_calls[+parts[0]]?.options.some(o=>o.id===parts[1]))state.choices[+parts[0]]=parts[1];}else if(act==='lineup')state.expandedLineup=state.expandedLineup===value?null:value;else if(act==='save-lineup'){const l=chosenLineups().find(x=>x.id===value);if(l&&!state.savedLineups.includes(value)){state.savedLineups.push(value);host.saveLineup(l);}}refresh();return true;}
function input(field,value,id){if(field==='text'){state.text=String(value);const button=typeof document!=='undefined'?document.querySelector('[data-act="fdfs-review"]'):null;if(button)button.disabled=!state.text.trim();return true;}if(field==='count'&&[5,10,25].includes(+value))state.count=+value;else if(field==='weight'&&state.picked.includes(id)&&+value>=0&&+value<=100&&+value%20===0)state.weights[id]=+value;else return false;refresh();return true;}
window.FantasyDfs={configure,render:page=>window.FantasyDfsTournament?window.FantasyDfsTournament.render(page):renderLegacy(page),renderLegacy,action,input,state,profile,chosenLineups};
})();
