/* Historical counts are display comparisons, separate from stored forecasts. */
(function(){'use strict';
const esc=x=>String(x==null?'':x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const glyph={hit:'✓',miss:'×',push:'=',missing:'—'};
function source(leg,season=2024){return (window.OutlookHistoryFixtures||[]).find(h=>h.player===leg.player&&h.market===leg.market&&h.season===season)||null;}
function classify(result,line,side){if(!Number.isFinite(result)||!Number.isFinite(line))return 'missing';if(result===line)return 'push';return (side==='Over'?result>line:result<line)?'hit':'miss';}
function results(leg,past,season=2024){const h=source(leg,season);return h?h.games.map(g=>Object.assign({},g,{target:past?g.line:leg.line,status:classify(g.result,past?g.line:leg.line,leg.side)})):[];}
function aligned(legs){const histories=legs.map(l=>results(l,false,2024).filter(g=>g.week>=1&&g.week<=8));if(histories.some(h=>!h.length))return [];return histories[0].map(g=>{const cells=histories.map(h=>h.find(r=>r.week===g.week));return {week:g.week,cells,available:cells.every(r=>r&&r.status!=='missing'),all:cells.every(r=>r&&r.status==='hit')};}).filter(r=>r.available);}
function summary(rows){const available=rows.filter(r=>r.status!=='missing').length,hits=rows.filter(r=>r.status==='hit').length;return {available,hits,percent:available?hits/available*100:null};}
function seasonSummary(leg,past,year){return Object.assign({season:year},summary(results(leg,past,year)));}
function plot(leg,past,season=2024){const rows=results(leg,past,season).slice(-8);if(!rows.length)return '<p class="ef-caption">Sample history unavailable for this player and market.</p>';const max=Math.max(1,...rows.flatMap(r=>[r.result||0,r.target||0]))*1.12,y=v=>112-v/max*88;const count=summary(rows);
return '<div class="ef-history-chart"><p class="ef-caption">Fictional '+season+' sample history · '+esc(past?leg.side+' '+leg.market+' · past lines':leg.side+' '+leg.line+' '+leg.market)+'</p><svg viewBox="0 0 320 174" role="img" aria-label="'+esc(rows.map(r=>'Week '+r.week+': '+r.result+', line '+r.target+', '+r.status).join('; '))+'">'+rows.map((r,i)=>{const x=24+i*39;return '<g class="ef-history-'+r.status+'">'+(Number.isFinite(r.result)?'<rect x="'+(x-10)+'" y="'+y(r.result)+'" width="20" height="'+(112-y(r.result))+'" rx="3"/><text x="'+x+'" y="14" text-anchor="middle">'+r.result+'</text>':'')+(Number.isFinite(r.target)?'<line x1="'+(x-14)+'" x2="'+(x+14)+'" y1="'+y(r.target)+'" y2="'+y(r.target)+'"/>':'')+'<text x="'+x+'" y="128" text-anchor="middle">W'+r.week+'</text><text class="ef-history-line-label" x="'+x+'" y="145" text-anchor="middle">'+(Number.isFinite(r.target)?r.target:'—')+'</text><text x="'+x+'" y="163" text-anchor="middle">'+glyph[r.status]+'</text></g>';}).join('')+'</svg><p class="ef-history-count"><strong>'+count.hits+' of '+count.available+' hit</strong> · ✓ hit · × miss · = push · — missing</p><p class="ef-caption">Line labels / dashed marks = '+(past?'each game’s line':'your line '+esc(leg.line))+'. Past results, not a forecast.</p></div>';}
function seasonGames(leg,past,year){const rows=results(leg,past,year),count=summary(rows);return '<section class="ef-season-games"><h3>'+year+' · '+esc(leg.side+' '+leg.market)+'</h3><p class="ef-caption">'+rows.length+' recorded sample appearances · Week 9 bye</p><div class="ef-season-game-head"><span>Week</span><span>Result</span><span>'+(past?'Past line':'Your line')+'</span><span>Status</span></div>'+rows.map(r=>'<div class="ef-season-game" data-week="'+r.week+'"><span>'+r.week+'</span><strong>'+esc(r.result==null?'—':r.result)+'</strong><span>'+esc(r.target==null?'—':r.target)+'</span><span class="ef-history-'+r.status+'">'+glyph[r.status]+' '+r.status+'</span></div>').join('')+'<p><strong>'+count.hits+' of '+count.available+' hit</strong> · missing comparisons excluded</p><p class="ef-caption">✓ hit · × miss · = push · — missing. Past results, not a forecast.</p></section>';}
function differential(required,model){if(!Number.isFinite(required)||!Number.isFinite(model))return '';const gap=(model-required)*100,zero=Math.abs(gap)<1e-10,tone=zero?'neutral':gap>0?'positive':'negative';return '<div class="probability-comparison"><div class="ef-price-readout"><div><span>Chance your price needs</span><strong>'+(required*100).toFixed(1)+'%</strong></div><div><span>Chance all bets win</span><strong>'+(model*100).toFixed(1)+'%</strong></div></div><div class="probability-range '+tone+'" role="img" aria-label="Price needs '+(required*100).toFixed(1)+' percent; model '+(model*100).toFixed(1)+' percent"><i style="left:'+Math.min(required,model)*100+'%;width:'+Math.abs(gap)+'%"></i><b class="required" style="left:'+required*100+'%"></b><b class="modeled" style="left:'+model*100+'%"></b></div><p class="probability-difference '+tone+'">'+(zero?'0.0':(gap>0?'+':'−')+Math.abs(gap).toFixed(1))+' percentage points</p><p class="bb-independence">Assumes each bet is independent; bets in the same game may affect each other.</p></div>';}
function matrix(legs){const rows=aligned(legs);if(rows.length<8)return '<p class="ef-caption">Eight aligned sample games are unavailable.</p>';return '<section class="ef-cohit-matrix"><p class="ef-caption">Fictional 2024 · Weeks 1–8 · against these lines</p><table><thead><tr><th>Week</th>'+legs.map(l=>'<th>'+esc(l.player.split(' ').pop())+'<small>'+esc(l.side+' '+l.line)+'</small></th>').join('')+'<th>All hit</th></tr></thead><tbody>'+rows.map(r=>'<tr><th>'+r.week+'</th>'+r.cells.map(c=>'<td class="ef-history-'+c.status+'" aria-label="'+c.status+'">'+glyph[c.status]+'</td>').join('')+'<td class="'+(r.all?'ef-history-hit':'')+'" aria-label="'+(r.all?'All hit':'Not all hit')+'">'+(r.all?'✓':'—')+'</td></tr>').join('')+'</tbody></table><p><strong>'+rows.filter(r=>r.all).length+' of '+rows.length+' together</strong> · ✓ hit · × miss · = push</p><p class="ef-caption">Past results, not combined pricing.</p></section>';}
function combination(legs,joint){if(!Number.isFinite(joint))return '';const percent=p=>(p*100).toFixed(1)+'%';return '<section class="bb-combination-outlook" aria-label="Individual chances and chance all bets win"><h3>Every leg has to win</h3><div class="bb-combination-legs">'+legs.map((l,i)=>'<div><span><b>'+(i+1)+'</b>'+esc(l.player)+'</span><strong>'+percent(l.p_at_line)+'</strong><i style="--chance:'+l.p_at_line*100+'%"></i></div>').join('')+'</div><div class="bb-combination-final"><span>All '+legs.length+' together</span><strong>'+percent(joint)+'</strong><i style="--chance:'+joint*100+'%"></i></div><p>One losing leg means the parlay loses. The combined estimate assumes each bet is independent; same-game connections are not priced.</p></section>';}
window.OutlookHistory={source,classify,results,aligned,summary,seasonSummary,plot,seasonGames,differential,matrix,combination};
}());
